project:
  type: website
  preview:
    port: 2805

website:
  title: "PFactor.io"
  site-url: https://pfactor.io
  back-to-top-navigation: true
  favicon: /favicon.ico
  navbar:
    title: false
    background: dark
    logo: /static/images/pfactor-header-logo-inverted.png
    logo-href: /
    tools:
      - icon: facebook
        href: https://facebook.com/pfactor.io
  sidebar:
    style: floating
    contents:
      - section: "Getting Started"
        contents:
          - auto: getting-started/*
      - section: "Private Pilot"
        contents: 
          - auto: private-pilot/*
          - section: "Lesson Plans"
            contents:
              - auto: private-pilot/lesson-plans/*
      - section: "Resources"
        contents:
          - auto: resources/*
    collapse-level: 1
  page-footer: 
    left: "Copyright &copy; 2023, PFactor.io"
    center: "[Shared under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/)"
    right:
      - icon: facebook
        href: https://facebook.com/pfactor.io

execute:
  freeze: auto

format:
  html:
    theme: yeti
    linestretch: 1.5
    css: styles.css
    toc: true
    link-external-newwindow: true
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Barlow+Semi+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&family=Noto+Sans:ital,wght@0,100..900;1,100..900&DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap" rel="stylesheet">
    mainfont: "DM Sans"
    anchor-sections: true