project:
  type: website
  preview:
    port: 2805

website:
  title: "PFactor.io"
  back-to-top-navigation: true
  navbar:
    logo-href: /
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/charathram
  sidebar:
    style: docked
    contents:
      - section: PPL
        contents: 
          - auto: "private-pilot/getting-started"
          - auto: "private-pilot/lesson-plans"
    background: light
    collapse-level: 2
  page-footer: 
    left: "Copyright &copy; 2023, PFactor.io"
    center: "Shared under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International](http://creativecommons.org/licenses/by-nc-sa/4.0/) License"
    right:
      - icon: facebook
        href: https://facebook.com/pfactor.io

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



