project:
  type: website
  preview:
    port: 2805

website:
  title: "PFactor.io"
  site-url: https://pfactor.io
  back-to-top-navigation: true
  favicon: /favicon.ico
  navbar:
    title: false
    logo: /static/images/PFactor-Logo-Header.jpg
    logo-href: /
    tools:
      - icon: facebook
        href: https://facebook.com/pfactor.io
  sidebar:
    style: floating
    contents:
      - section: "Getting Started"
        contents:
          - auto: getting-started/*
      - section: "Private Pilot"
        contents: 
          - auto: private-pilot/*
      - section: "Resources"
        contents:
          - auto: resources/*
    collapse-level: 1
  page-footer: 
    left: "Copyright &copy; 2023, PFactor.io"
    center: "[Shared under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/)"
    right:
      - icon: facebook
        href: https://facebook.com/pfactor.io

format:
  html:
    theme: litera
    linestretch: 1.5
    css: styles.css
    toc: true
    link-external-newwindow: true
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Open+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Oswald:wght@400;500;600;700&display=swap" rel="stylesheet">
    mainfont: Merriweather
