project:
  type: website
  preview:
    port: 2805

website:
  title: "PFactor.io"
  navbar:
    logo-href: /
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/charathram
  sidebar:
    style: docked
    contents:
      - section: Private Pilot
        contents: 
          - auto: "private-pilot/getting-started"
          - auto: "private-pilot/lesson-plans"
    background: light
    collapse-level: 2

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



