project:
  type: website
  preview:
    port: 2805

website:
  title: "PFactor.io"
  site-url: https://pfactor.io/
  back-to-top-navigation: true
  navbar:
    logo-href: /
    tools:
      - icon: facebook
        href: https://facebook.com/pfactor.io
  sidebar:
    style: docked
    contents:
      - section: "Private Pilot"
        contents: 
          - auto: "private-pilot/getting-started"
          - auto: "private-pilot/lesson-plans"
    collapse-level: 2
  page-footer: 
    left: "Copyright &copy; 2023, PFactor.io"
    center: "[Shared under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/)"
    right:
      - icon: facebook
        href: https://facebook.com/pfactor.io

format:
  html:
    theme: lux
    fontsize: 1.2em
    linestretch: 1.5
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/pfactor\.io\/custom
  pdf: 
    number-sections: false
    shift-heading-level-by: -1
    classoption: sfdefaults=false
    header-includes: |
      \usepackage{fancyhdr}
      \pagestyle{fancy}
      \fancyhf{}
      \renewcommand{\headrulewidth}{0pt}
      \renewcommand{\footrulewidth}{0.1pt}
      \fancyfoot[L]{\copyright\ 2023, PFactor.io}
      \fancyfoot[R]{\thepage}
      \fancyfoot[C]{\href{http://creativecommons.org/licenses/by-nc-sa/4.0/}{CC BY-NC-SA 4.0}}


