---
listing:
  id: listings
  sort: "date desc"
  categories: true
  type: grid
  fields: [image, date, title, subtitle, author, categories]
  grid-columns: 2
  max-items: 10
  exclude:
    title: "About"
format:
  html:
    toc: false
---

::: {.c}
TEST
:::

# PFactor.io

Thank you for visiting my web site. My name is Charath Ranganathan and I am a CFII based in sunny Southern California. I teach at the [Aero Association of California Institute of Technology](https://aacit.org/) (AACIT), often known as the "Caltech/JPL Flying Club."

As a lifelong aviation enthusiast, avid flight simmer, and AvGeek, I am happiest when I'm in the air. I consider it a privilege to guide you in your aviation journey.

My goal is to make this site one of the most sought-after resources for those embarking on their aviation journey. The site and its contents will always be free.

# Using this site

The sidebar on your left will take you to the articles, lessons, and other material on the site. However, for your convenience, the 10 most recent articles published on the site are listed below.

# Recent Articles

::: {#listings}
:::